#!/usr/bin/env bash
set -eu -o pipefail

die() {
    local exitcode="$1"; shift
    [[ -z $1 ]] || echo 1>&2 "$@"
    exit $exitcode
}

setup_asxxxx() {
    local archive=5p31_exe_linux.zip
    local dldir="$basedir/.download"
    local instdir="$builddir/bin"
    local url='http://shop-pdp.net/_ftp/asxxxx'
    local sha=648a11d48daab3b67e97d82221315b074e874ea30b3f0ead2836baec211940c7

    PATH="$builddir/bin:$PATH"

    [[ -x $instdir/aslink && -x $instdir/as6500 ]] && return

    sha256sum --version >/dev/null || die 3
    local shacheck=$(sha256sum "$dldir/$archive" 2>/dev/null)
    [[ ${shacheck%% *} = $sha ]] || {
        echo "Downloading $archive"
        curl --create-dirs -o "$dldir/$archive" -L "$url/$archive"
    }

    unzip -h >/dev/null || die 3
    mkdir -p "$instdir"
    (cd "$instdir" && unzip -qo "$dldir/$archive" && chmod +x as* s19os9*)

    #   Here it would be nice to run "$instdir"/aslink and print out
    #   what went wrong if it fails (usually because we can't run
    #   32-bit executables), but that's difficult because getting the
    #   help message returns an error exit code.
}

setup_asl() {
    . tools/asl/Build
    PATH="$builddir/asl:$PATH"
    asl_installed && return 0
    install_asl "$builddir/asl"
}

####################################################################
#   Main

basedir=$(cd "$(dirname "$0")" && pwd -P)
builddir="$basedir/.build"

#   Leading command line args (these must be at the start):
#   • -C: clean rebuild of everything, including toolchains
#   • -c: clean rebuild of only this repo's source (test/toolchain output)
#   All args after these are passed on to pytest.
while [[ ${#@} -gt 0 ]]; do case "$1" in
    -C)     shift; rm -rf "$builddir";;
    -c)     shift; rm -rf "$builddir"/{obj,pytest};;
    *)      break;;
esac; done

cd "$basedir"

setup_asxxxx
setup_asl
. ./activate -q

mkdir -p "$builddir/obj"

####################################################################
#   ASxxxx builds
#
#   The files to build are currently hardcoded with
#   no dependency graph so it rebuilds everything each time.
#   (Fortunately this is quite fast.)

#   -x  Output in hexadecimal
#   -w  Wide listing format for symbol table (55 char of symname instead of 14)
#   -p  Disable listing pagination
#   -l  Create listing file (`.lst`)
#   -o  Create object file (`.rel`)
#   -s  Create symbol file (`.sym`) (removes symtab from listing file)
#   -r  Inlcude assembler line numbers in the `.hlr` hint file
#   -rr Inlcude non-list assembler line numbers in the `.hlr` hint file
asmopts="-xwplo -f"

#   -n  No echo of commands to stdout
#   -u  Update listing file (`.lst`) with relocated addresses info (`.rst`)
#       (This does not update the addresses in the symbol table.)
#   -m  Generate map output file (`.map`)
#   -w  "Wide" mode for map file (show 32 chars, not 8, of symbol names)
#   -t  Output format: Tandy Color Computer BASIC binary file (`.bin`)
linkopts="-numwt"

asm() {
    local srcfile="$1"; shift
    #   `.rel` output extension is replaced/added automatically
    as6500 $asmopts "$builddir/obj/"$(basename "$srcfile") "$srcfile" "$@"
}

link() {
    #   First filename is outputfile; extn replaced by .hex/.s19/.bin.
    #   Subsequent filenames are input files, with or without .rel extension
    #   Single filename is ouput and input.
    #   Other arguments before and after
    (cd $builddir/obj/ && aslink $linkopts "$@")
}

asm src/simple-asx.a65  ; link simple-asx
asm src/c64.a65         ; link c64
asm src/reloctest.a65   ; link reloctest -b '_code=0x400' reloctest
asm src/objects.a65     ; link objects   -b '_code=0x1000' objects
asm src/zptest.a65      ; link zptest    -b '_code=0x0300'

#   Replace form feeds since we view listing only on screen. This must
#   be done *after* the .rst file is created by the linker because
#   otherwise the extra newlines make the linker edit the wrong lines
#   in the .lst file.
sed -i -e 's/\f/\n/' "$builddir"/obj/*.{lst,rst,map}

####################################################################
#   AS builds

asbuild() {
    local srcpath="$1"; shift
    local objsubdir=$(dirname "$srcpath")
          objsubdir=${objsubdir#$basedir/}  # Remove $basedir prefix if present
    local objdir="$basedir/.build/obj/$objsubdir"
    local src=$(basename "$srcpath")
    #   AS has some poor behaviour we need to work around here.
    #   • We set CWD to output dir because AS can't specify other output
    #     locations for some files, such as the debug symbols.
    #   • If given an absolute path to a source file in another dir, AS
    #     doesn't generate output files. (!) So we set up the top-level
    #     source file here that `include`s the real top-level source file.
    #   • </dev/null prevents interactive prompt if no input file given.
    #   • Full path to source file must be given. It will be found from
    #     path relative to include dir, but then AS will crash.
    #   Also, We make symbols case sensitive here; this can be done only
    #   with a command-line option.
    mkdir -p "$objdir"
    (cd "$objdir" \
        && echo  >"$src" '   page 0' \
        && for line in "$@"; do echo >>"$src" "$line"; done \
        && echo >>"$src" "   include $srcpath" \
        && asl </dev/null -qxx -U \
            -i "$basedir" "$src" -L -s -g
    )
}

asbuild src/asl-nomacro.a65
asbuild src/simple-asl.a65  ';  Unit Test Assembly' '   org $240'
asbuild src/stdtest.a65     \
    '   cpu 6502' '   include "src/std.a65"' '   org $240'
asbuild src/bigint.a65      \
    '   cpu 6502' '   include "src/std.a65"' '   org $1000'

####################################################################
#   Tests

export PYTHONPATH="$basedir/lib"
#   XXX This probably relies on the cwd to find the pytest.ini.
pytest -q "$@"
