#!/usr/bin/env bash
set -eu -o pipefail

die() {
    local exitcode="$1"; shift
    [[ -z $1 ]] || echo 1>&2 "$@"
    exit $exitcode
}

download_asxxxx() {
    local archive=5p31_exe_linux.zip
    local dldir="$basedir/.download"
    local instdir="$builddir/bin"
    local url='http://shop-pdp.net/_ftp/asxxxx'
    local sha=648a11d48daab3b67e97d82221315b074e874ea30b3f0ead2836baec211940c7

    [[ -x $instdir/aslink && -x $instdir/as6500 ]] && return

    sha256sum --version >/dev/null || die 3
    local shacheck=$(sha256sum "$dldir/$archive" 2>/dev/null)
    [[ ${shacheck%% *} = $sha ]] || {
        echo "Downloading $archive"
        curl --create-dirs -o "$dldir/$archive" -L "$url/$archive"
    }

    unzip -h >/dev/null || die 3
    mkdir -p "$instdir"
    (cd "$instdir" && unzip -qo "$dldir/$archive" && chmod +x as* s19os9*)

    #   Here it would be nice to run "$instdir"/aslink and print out
    #   what went wrong if it fails (usually because we can't run
    #   32-bit executables), but that's difficult because getting the
    #   help message returns an error exit code.
}

basedir=$(cd "$(dirname "$0")" && pwd -P)
builddir="$basedir/.build"

download_asxxxx
. ./activate -q

export PATH="$builddir/bin:$PATH"
cd "$basedir"
mkdir -p "$builddir/obj"

as6500 -l -o "$builddir/obj/simple.rel" src/simple.a65
#   Replace form feeds since we view listing only on screen.
sed -i -e 's/\f/\n/' "$builddir/obj/simple.lst"
