#!/usr/bin/env python3
'''
    Configure for use of dos33fs-utils used for manipulating
    Apple II files and DOS 3.3 disk images.

    This will fetch from `source_repo` and build the `source_ref`
    branch, if necessary.

    See the module documentation for `setup` for more details.
'''

from    os.path  import abspath, dirname
import  sys

sys.path.insert(0, abspath(dirname(dirname(__file__)))) # setup.py location
from setup import *

class DOS33FS(Setup):

    def __init__(self):
        super().__init__()
        self.source_repo = 'https://github.com/deater/dos33fsprogs.git'

    def check_installed(self):
        return checkrun( ['dos33', '-h'], 0,
            b'by Vince Weaver <vince@deater.net>')

    def configure(self):
        deps = [ 'liblz4-dev', 'libpng-dev', ]
        self.check_packages(debian=deps)

    def build(self):
        self.make_src()

    def install(self):
        dos33 = 'utils/dos33fs-utils'
        basic = 'utils/asoft_basic-utils'
        bins = (
            (dos33,             'char2hex'),
            (dos33,             'dos33'),
            (dos33,             'dos33_text2ascii'),
            (dos33,             'make_b'),
            (dos33,             'mkdos33fs'),
            (basic,             'asoft_compact'),
            (basic,             'asoft_detoken'),
            (basic,             'bin2data'),
            (basic,             'integer_detoken'),
            (basic,             'tokenize_asoft'),
            ('bmp2dhr',         'b2d'),
            )
        for subdir, file in bins:
            dest = self.pdir('bin').joinpath(file)
            if not dest.exists():
                dest.symlink_to(self.srcdir().joinpath(subdir, file))

if (__name__) == '__main__':
    DOS33FS().main()
