#!/usr/bin/env python3
'''
    Configure for use of the Macroassembler AS.

    This will fetch from `ASL.source_repo` and build the `ASL.source_ref`
    branch, if necessary.

    See the module documentation for `setup` for more details.
'''

from    os.path  import abspath, dirname
import  shutil, subprocess, sys, traceback

sys.path.insert(0, abspath(dirname(dirname(__file__)))) # setup.py location
from setup import *

class ASL(Setup):

    def toolset_name(self):
        return 'asl'

    def source_repo(self):
        return 'https://github.com/KubaO/asl.git'

    def source_ref(self):
        return 'dev/cjs/current'

    def check_installed(self):
        ''' *Silently* determine if the toolset is currently available or
            not and exit with success if it is.
        '''
        #   XXX Start with shutil.which, first?
        try:
            c = subprocess.run(['asl', '-this-is-not-an-option'],
                stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
        except FileNotFoundError:
            return
        if c.returncode == 4 and b'Invalid option' in c.stdout:
            successexit()

    def fetch(self):
        ''' Fetch the tool if not already present in TARGET. '''
        if self.srcdir().is_dir():
            print('----- Using existing source in {}'.format(self.srcdir()))
            return

        print('----- Cloning {} from {}'.format(
            self.toolset_name(), self.source_repo()))
        runcmd([ 'git', 'clone', str(self.source_repo()), str(self.srcdir()) ])

        print('----- Switching to ref or branch {}'.format(self.source_ref()))
        runcmd([ 'git', '-C', str(self.srcdir()),
            'checkout', str(self.source_ref()) ])

    def configure(self):
        ''' Configure build, if not already done. '''
        if self.srcdir().joinpath('Makefile.def').exists():
            print('----- Using existing build configuration')
            return

        print('----- Configuring {}'.format(self.srcdir()))

        shutil.copyfile(
            str(Path(__file__).parent.joinpath('gitignore')),
            str(self.srcdir().joinpath('.gitignore')))
        shutil.copyfile(
            str(self.srcdir().joinpath(
                'Makefile.def-samples', 'Makefile.def-x86_64-unknown-linux')),
            str(self.srcdir().joinpath('Makefile.def')))

    def build(self):
        ''' Build  the tool.

            This is generally expected to rebuild the tool if any files have
            changed in the local source copy.
        '''
        #   Note we avoid building the documentation here.
        runcmd(['make', '-j8'], cwd=self.srcdir())

    def install(self):
        ''' For ASL we don't use `make install` because that wants to build the
            documentation, which requires LaTeX and even then tends to drop to
            interactive prompts about missing `german.sty` etc.

            As well, it's nicer four our purposes to use symlinks back to the
            build directory because then a developer tweaking AS can just
            `make` in the source directory to make the new version available to
            the build system.

            So instead we emulate the parts of install.{bat,cmd,sh} we want,
            which is bin/, lib/ (the message files are required) and include/.
        '''

        binfiles = ('asl', 'plist', 'alink', 'pbind', 'p2hex', 'p2bin',)
        for f in binfiles:
            dest = self.pdir('bin').joinpath(f)
            if not dest.exists(): dest.symlink_to(self.srcdir().joinpath(f))

        #   The localization message files normally go in lib/asl/, but the
        #   programs don't find them there by default (unless perhaps the
        #   prefix is /usr/local/). We could emit a setting for the AS_MSGPATH
        #   environment variable to indicate where they are, but to allow use
        #   of these tools from the command line without running the Setup
        #   script, it seems better to just drop the files into bin/, where the
        #   programs can automatically find them.
        #
        for path in self.srcdir().glob('*.msg'):
            dest = self.pdir('bin').joinpath(path.name)
            if not dest.exists(): dest.symlink_to(path)

        srcs = self.srcdir().joinpath('include')
        for src in srcs.glob('**/*'):
            if src.is_dir(): continue
            dest = self.pdir('include', 'asl').joinpath(src.relative_to(srcs))
            dest.parent.mkdir(parents=True, exist_ok=True)
            if not dest.exists(): dest.symlink_to(src)

    def main(self):
        self.setbuilddir()
        self.setpath()
        self.check_installed()
        if not self.builddir:
            errexit(EX_USAGE,
                'BUILDDIR not set and {} is not a directory.'.format(BUILDDIR))
        else:
            self.fetch()
            self.configure()
            self.build()
            self.install()

####################################################################
#   Main program

if (__name__) == '__main__':
    try:
        ASL().main()
    except Exception as ex:
        printconfig('return', EX_SOFTWARE)
        errprint('INTERNAL ERROR in', sys.argv[0])
        traceback.print_exc()
        sys.exit(EX_SOFTWARE)
