from    testmc.asxxxx import ParseBin

#   Records in "Tandy CoCo Disk BASIC binary" (.bin) format as
#   generated by the ASxxxx assembler's `aslink` program.
BINDATA = bytes.fromhex(''
    # typ  len addr data
    + '00 0001 0123 ee'
    + '00 0009 0400 8a 8c09 0418 6d09 0460'
    + 'ff 0000 0403'    # final record has entry point
    )

def test_ParseBin():
    p = ParseBin(BINDATA)
    rec0data = [0xee]
    rec1data = [0x8a, 0x8c, 0x09, 0x04, 0x18, 0x6d, 0x09, 0x04, 0x60]
    assert (0x0123, rec0data) == p[0]
    assert (0x0400, rec1data) == p[1]
    #   Entries only for data records, not the entrypoint record
    assert 2 == len(p)
    assert 0x0403 == p.entrypoint
