#!/usr/bin/env bash
set -eu -o pipefail

url='http://www.callapple.org/soft/ap1/emul/'
archive='Apple1_bios.zip'

dldir='../.download'

cd "$(dirname "$0")"
[[ -r $dldir/$archive ]] \
    || curl --create-dirs -o "$dldir/$archive" -L "$url/$archive"
unzip -u "$dldir/$archive"

#   For some reason the POM1 dump is different from the
#   Call-A.P.P.L.E. dump in the last 25% or so.
pom1rom=pom1-charmap.rom
[[ -r $pom1rom ]] || curl -o pom1-charmap.rom -L \
    https://github.com/anarkavre/pom1/raw/master/src/roms/charmap.rom
