#!/usr/bin/env bash
set -eu -o pipefail

B8_PROJDIR=$(cd "$(dirname "$0")/.." && pwd -P)
dldir="$B8_PROJDIR/.download"

url='http://www.callapple.org/soft/ap1/emul/'
archive='Apple1_bios.zip'   # Contains:
#   • apple1.rom ( 256 bytes) WozMon
#   • apple1.vid:(1024 bytes) character ROM for video generator

[[ -r $dldir/$archive ]] \
    || curl --create-dirs -o "$dldir/$archive" -L "$url/$archive"
#unzip -u "$dldir/$archive"

#   For some reason the POM1 dump is different from the
#   Call-A.P.P.L.E. dump in the last 25% or so.
pom1rom="$dldir/pom1-charmap.rom"
[[ -r $pom1rom ]] || curl -L -o "$pom1rom" \
    https://github.com/anarkavre/pom1/raw/master/src/roms/charmap.rom
